added roadmap information
HackerHappyHour/reveal pull request #12
Opened 2019-03-15 17:56 UTC by LongLiveCHIEF

Included some bits about our roadmaps and projects, and added a bit more about the intent of our fork moving forward.

One distinction I think it is important to make from the original fork, is that instead of this being a" HTML based" presentation framework, it's a "web-based" presentation framework. I think as we modernize this library, more features like the existing markdown support will allow this library to use many markup formats
and templating tools to create presentation slides and content.

I also updated the License copyright line that we missed with the LICENSE file update, and added some EOL returns for readability in non-wrapping editors.

2019-03-15 21:10 UTC, cujarrett approved these changes
👍

2019-03-15 21:10 UTC, cujarrett commented
> looks to pull as many existing PR's from the upstream project as possible, and bring the reveal project up to speed with modern tooling, api design, and front-end features.

This is great!

2019-03-15 21:23 UTC, nickshine requested changes
@LongLiveCHIEF just a few minor things I caught looking at the file in preview mode.

2019-03-15 21:23 UTC, nickshine commented on README.md
> +to continue active development and feature contributions to reveal.js. Upstream of this fork
Not sure how I got the 'Upstream' word mixed in there.. it doesn't make sense when you read the full sentence.
```suggestion
to continue active development and feature contributions to reveal.js. This fork 
```

2019-03-15 21:23 UTC, nickshine commented on README.md
> +Our most important goals are currently tracked in our [projects][] and [milestones][]. In particular the [v2 milestone][]
Either need `[v2 roadmap]` ref link here or change the link definition at bottom to `[v2 milestone]`.
```suggestion
Our most important goals are currently tracked in our [projects][] and [milestones][]. In particular the [v2 milestone][v2 roadmap]
```

2019-03-15 21:23 UTC, nickshine commented on README.md
>  Copyright (C) 2018 Hakim El Hattab, http://hakim.se
Adding 2 spaces for proper newline before added "Modified work  ..." line.
```suggestion
Copyright (C) 2018 Hakim El Hattab, http://hakim.se   
```

2019-03-16 22:41 UTC, nickshine approved these changes

2019-03-16 22:42 UTC, merged